[package]
name = "loko"
description = "Task scripting"
version = "0.1.0"
edition = "2021"
license = "MIT"
documentation = ""
repository = ""
homepage = ""
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
